### ISSUE TITLE
Stuck on [EB|#LOG:EXITBS:START] with nearly identical configuration

### ISSUE THREAD

**Issue by agramian** [khronokernel/OpenCore-Asus-X299#1]
## Description

I'm having trouble booting with this same motherboard/platform.

I followed the config guide for [Skylake-X/W and Cascade Lake-X/W](https://dortania.github.io/OpenCore-Install-Guide/config-HEDT/skylake-x.html) and tried the suggestions from the [Stuck on [EB|#LOG:EXITBS:START]](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#stuck-on-eb-log-exitbs-start) in the OpenCore Install Guide General Troubleshooting section.  I was still unable to boot so I tried adjusting my config based on the information from this repo including replacing the SSDTs with the compiled versions provided here.  Still no luck.

I realize you added the disclaimer that this system was built with BIOS Version 2002 however because of the references to version 3006 which I am on I was hoping it would work as well.  I have tried rolling back to version 2002 but unfortunately it does not seem like ASUS allows it as I'm getting an error saying "Selected file is not a proper BIOS".  Even using AFUDOS does not work for downgrading.

Any help or suggestions are greatly appreciated.
Let me know if I can provide any other specific info would be helpful to debug.
Thank you for your efforts on OpenCore.

### Hardware
ROG STRIX X299-E GAMING 
BIOS Version 3006
i7-7820X
BIOS settings are attached.

### OS
macOS Catalina 10.15.6

### OpenCore
OpenCore-0.6.0-DEBUG
The Kexts used are all DEBUG versions where available. 
The config and debug log are attached.
 
[X299 Boot Issue FIles.zip](https://github.com/khronokernel/OpenCore-Asus-X299/files/5155201/X299.Boot.Issue.FIles.zip)

**Comment by khronokernel** [comment]
> BIOS Version 3006

Try BIOS v3105, I just updated a few days ago to test a bug with DevirtuliseMmio and system boots fine. Only issue is AWAC however I believe this repo includes the fix(gonna be honest I forgot I had this repo haha). And there's also no need for CFG-lock kernel patches, Asus fixed that bug in 3105

**Comment by agramian** [comment]
I just upgraded to BIOS v3105, removed the CFG-lock kernel patches, and tried again but it still gets stuck at the same spot.

When you say the AWAC fix is included in this repo you're referring to [SSDT-RTC0-RANGE-v3006.aml](https://github.com/khronokernel/OpenCore-Asus-X299/blob/master/ACPI-Compiled/SSDT-RTC0-RANGE-v3006.aml), right?
I originally tried my config with the full/bloated versions of the SSDTs from the main install guide but then replaced them with the ones provided here.
I'm not using [SSDT-AWAC.aml](https://dortania.github.io/Getting-Started-With-ACPI/Universal/awac.html) since my understanding is that you would either use SSDT-AWAC or SSDT-RTC0-RANGE but not both.

I also tried removing [SSDT-RTC0-RANGE-v3006.aml](https://github.com/khronokernel/OpenCore-Asus-X299/blob/master/ACPI-Compiled/SSDT-RTC0-RANGE-v3006.aml) and only defining Fix RTC Range under ACPI -> Patch as noted in the repo but that didn't do it either.

Is it possible that I just need to wait for a while to get past this point (>30 minutes) and that it's just extremely slow since I'm using DEBUG versions of OpenCore and all the Kexts?

I also notice that in this repo you define a PCI device `PciRoot(0x0)/Pci(0x1F,0x3)` but in my config I removed the one PCI device from the sample as the main install guide suggested.
Could that make a difference?

Does it matter that I've disabled the SATA controllers in BIOS since I'm only using an M.2 drive?

The files I attached to the original post are still relevant besides these small tweaks to the CFG-lock and other patches you suggested trying.

If I need to manually compile the SSDTs I will try that but I don't want to go through that effort until I'm sure that this isn't just an issue with the main config especially since this repo uses the same motherboard/platform already.

Thanks for helping and please let me know if I can provide any more detail to help identify the cause here.

**Comment by agramian** [comment]
I think I figured it out.  I set `SetupVirtualMap` to `false` and have at least gotten the installer to boot.
It would be helpful to add this to the Booter Quirks section of this repo.

**Comment by khronokernel** [comment]
Oh that is quite odd, will add a note. I never booted with SetupVirtualMap, though for some reason never added it to the docs. Seems the newer builds of EDKII Asus is pushing breaks that quirk, I assumed only Comet lake boards were getting that

**Comment by agramian** [comment]
Ok I was able to successfully install macOS 10.15.6 but I noticed a lot of instability and although Safari works, opening Google Chrome immediately locks up the entire system.  Whenever I rebooted the system the os attempted to reopen the previous windows and so it just kept crashing as soon as I logged back in.

I tried installing macOS 10.15.5 instead since it's the latest version explicitly stated as compatible on the main dortania site but the issues are the same.

Do you have any suggestions or could you provide your full OpenCore 0.6.0 config by chance?

**Comment by khronokernel** [comment]
> I tried installing macOS 10.15.5 instead since it's the latest version explicitly stated as compatible on the main dortania site

Where'd you read that? No where in the guide does it have explicitly supported versions of macOS

Either way here's my EFI, main things I changed were serial output(as I doubt you have that setup) and serials removed:
* [EFI.zip](https://github.com/khronokernel/OpenCore-Asus-X299/files/5163413/EFI.zip)

You most likely have some GPU issue if Chrome's locking up

**Comment by agramian** [comment]
Oh ok I misunderstood about the supported/safe versions of macOS.

Yep this was a GPU issue.   I was following the main X299 install guide example and used the iMacPro1,1 SMBIOS but my GPU is an R9 Nano so switching to the MacPro6,1 SMBIOS resolved the instability.  Everything seems to be working great on macOS Catalina 10.15.6 including Warp Stabilizer and plugins in Adobe Premiere which were not working with my other Ryzen system. 

Thanks again for your patience helping me through this.  This issue can be closed out.
